apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-analyzer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-analyzer
  template:
    metadata:
      labels:
        app: cv-analyzer
    spec:
      containers:
        - name: cv-analyzer
          image: cv-analyzer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: cv-analyzer-service
  namespace: default
spec:
  selector:
    app: cv-analyzer
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080