apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-analyzer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-analyzer
  template:
    metadata:
      labels:
        app: cv-analyzer
    spec:
      containers:
        - name: cv-analyzer
          image: cv-analyzer:local
          # expose container port that FastAPI listens on
          ports:
            - containerPort: 8000
          env:
            # inject the OpenAI API key from the Kubernetes secret
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: cv-analyzer-service
  namespace: default
spec:
  selector:
    app: cv-analyzer
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080