apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-analyzer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-analyzer
  template:
    metadata:
      labels:
        app: cv-analyzer
    spec:
      containers:
        - name: cv-analyzer
          # ⚠️ Use a dynamic tag to force updates (replace :local at deploy time)
          image: cv-analyzer:latest
          imagePullPolicy: IfNotPresent   # prevents pulling from Docker Hub (important when using minikube image load)
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
          # Optional but recommended for production stability:
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cv-analyzer-service
  namespace: default
spec:
  selector:
    app: cv-analyzer
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080